<?php

function inline_form_errors_preprocess_status_messages(&$vars){
  $inline_form_errors = backdrop_get_messages('inline_form_errors');

  if(!empty($inline_form_errors['inline_form_errors'])){
    $links = array();
    foreach($inline_form_errors['inline_form_errors'] as $inline_error){
      // remove the existing error message
      $key = array_search($inline_error['error'], $_SESSION['messages']['error']);
      if ($key !== false){
        unset($_SESSION['messages']['error'][$key]);
      }

      // build jump link from top-level item
      $links[] = "<a href='#{$inline_error['id']}'>{$inline_error['label']}</a>";
    }

    if(count($links)){
      backdrop_set_message(format_plural( count($links), '1 error has', '@count errors have'). ' been found: ' . implode(', ', $links), 'error' );
    }
  }
}

function inline_form_errors_preprocess_form_element(&$vars){
  $element = &$vars['element'];
  $form_errors = form_get_errors();
  //$inline_form_errors = &backdrop_static('inline_form_errors', array());

  if (!empty($form_errors)){
    foreach($form_errors as $error_name => $error){
      $error_parents = explode('][', $error_name);
      $error_grandparents = $error_parents;
      array_pop($error_grandparents);

      $normalized_parents = array_map('strval',$element['#parents']);
      if ($error_parents === $normalized_parents || $error_grandparents === $normalized_parents)
      {
        // this error belongs to this element
        $label = $element['#title'];

        // find the label
        if (!$label && isset($element['#instance'])){
          $label = $element['#instance']['label'];
        }
        if (!$label && isset($element['#entity_type'], $element['#bundle'])){
          $instance = field_info_instance($element['#entity_type'], $element['#parents'][0],$element['#bundle']);
          $label = $instance['label'];
        }

        // custom id, so we don't have to care what the form provides
        $anchor_id = backdrop_html_id('inline-error-' . implode('-', $element['#parents']));

        // save the error somewhere we can use it later
        backdrop_set_message(array(
          'id' => $anchor_id,
          'label' => $label,
          'error' => $error,
          'error_name' => $error_name,
        ), 'inline_form_errors');

        $element['#title'].= "<a class='inline-form-error-link' id='{$anchor_id}'></a>";
        $element['#children'].= "<div class='messages error'>{$error}</div>";
      }
    }
  }
}